### ISSUE TITLE
can't find explanation how to get PASS1_FREQUENCIES and also PASS2_FREQUENCIES 

### ISSUE THREAD

**Issue by mahmoudSobhiAwad** [khaledwaleedsamir/Super-Hetrodyne-Receiver#1]
please could you provide me a method of how you can get these parameters ?

**Comment by khaledwaleedsamir** [comment]
The pass and stop frequencies are estimated from the spectrum of the generated signals after modulation roughly, and you can also get it if you plot the spectrum of the original sound and find its baseband bandwidth, the passband bandwidth is 2x baseband bandwidth centered around the carrier frequency so pass1 is fc-bbbw and pass2 is fc+bbbw.
![image](https://github.com/khaledwaleedsamir/Super-Hetrodyne-Receiver/assets/104536807/113f978c-3d07-418e-a6c2-ba920b164d75)

**Comment by modyelgen** [comment]
okay i understand how to get pass frequencies but stop i don't ! could you help me with that ?

**Comment by khaledwaleedsamir** [comment]
This is the definition of Fstop1&2 and Fpass1&2 from MATLAB filter designer shown in the image below, the region between Fstop2 and Fpass2 is the transition region from no attenuation to high attenuation (as it is not an ideal filter) and the same applies for Fstop1 and Fpass1 so on based on the spectrum of the FDM signal transmitted i.e. number of signals sent, the guard bands between the different messages sent, carrier frequency etc. you should select the values of those parameters.
![image](https://github.com/khaledwaleedsamir/Super-Hetrodyne-Receiver/assets/104536807/c4a21a2b-62f5-4d3d-ae18-9899babd8b84)

**Comment by mahmoudSobhiAwad** [comment]
thx good explanation and clean code. may allah bless you
